question2and3: GLApplication.cpp AdjustableCamera.h ActiveMesh.h BasicShaderMaterial.h ColouredTextureMaterial.h Material.h Mesh.h StaticMesh.h Texture.h TextureShaderMaterial.h utilityFunctions.h ActiveMesh.cpp BasicShaderMaterial.cpp ColouredTextureMaterial.cpp Mesh.cpp StaticMesh.cpp Texture.cpp TextureShaderMaterial.cpp
	g++ GLApplication.cpp AdjustableCamera.h ActiveMesh.h BasicShaderMaterial.h ColouredTextureMaterial.h Material.h Mesh.h StaticMesh.h Texture.h TextureShaderMaterial.h utilityFunctions.h ActiveMesh.cpp BasicShaderMaterial.cpp ColouredTextureMaterial.cpp Mesh.cpp StaticMesh.cpp Texture.cpp TextureShaderMaterial.cpp -o ../question2and3 -I/usr/include -L/usr/lib -lGLEW -lglut -lGL -lGLU -lX11 -g
clean:
	-rm -f  ../question2and3 core output.bvh
